version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules
    restart: always
    ports:
      - 3000:3000
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
